
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/drizzs/GrassWorld-1.14/issues"
[[mods]]
modId="grassworld"
version="${2.0.0}"
displayName="Grass World"
displayURL="https://www.curseforge.com/minecraft/mc-mods/grassworld"
logoFile="examplemod.png"
credits="Artist: DinoSoup / VeyezX, Also Special Thanks to Team RAM and SkySom for helping me start coding and encouraging me!"
authors="Drizzs"
description='''
This mod adds grass blocks of different types for the overworld, as well as the end and nether!
This mod was made primarily for cosmetic purposes! Send us your screenshots of how you used the mod!
'''

